group = 'org.hl7.fhir'
version = '0.0.1'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
	mavenLocal()
	mavenCentral()
    flatDir {
	    dirs 'libs'
    }
}

dependencies {

	implementation project(':fhirjson-jackson')
	implementation libs.fhirEmf
	api libs.graphulo
	implementation libs.accumulo
	implementation libs.context
	implementation libs.slf4jAPI
	implementation libs.logbackClassic

	// EMF
	implementation libs.emfCommon
	implementation libs.emfEcore
	implementation libs.emfEcoreXMI
}

tasks.named('test') {
	useJUnitPlatform()
}
