group = 'org.hl7.fhir'
version = '0.0.1'

java {
    sourceCompatibility = JavaVersion.VERSION_17
    targetCompatibility = JavaVersion.VERSION_17
}

repositories {
	mavenLocal()
	mavenCentral()
    flatDir {
	    dirs 'libs'
    }
}

dependencies {

	implementation libs.fhirEmf
	api libs.graphulo
	implementation libs.accumulo
	implementation libs.context
	implementation libs.slf4jAPI
	implementation libs.logbackClassic

    testImplementation libs.junitJupiter
    testImplementation libs.junitJupiterAPI
}

tasks.named('test') {
	useJUnitPlatform()
}

